version: "3.9"
services:
  ui:
    container_name: "vue-app"
    build: ./spa
    image: ahurtadoc/ui:latest
    ports:
      - "80:80"
    networks:
      - inet
    depends_on:
      - "server"
  server:
    container_name: "go-app"
    build: ./server
    image: ahurtadoc/server:latest
    restart: "always"
    environment:
      - PORT=4001
    ports:
      - "4001:4001"
    networks:
      - inet
networks:
  inet:
    driver: overlay
    attachable: true
